const COUNTRY_NAMES: Record<string, string> = {
  AFG: 'Afghanistan',
  ARM: 'Armenia',
  AZE: 'Azerbaijan',
  BFA: 'Burkina Faso',
  BGD: 'Bangladesh',
  CAF: 'Central African Rep.',
  CIV: "Côte d'Ivoire",
  CMR: 'Cameroon',
  COD: 'DR Congo',
  COL: 'Colombia',
  DZA: 'Algeria',
  ECU: 'Ecuador',
  EGY: 'Egypt',
  ERI: 'Eritrea',
  ETH: 'Ethiopia',
  GIN: 'Guinea',
  GNB: 'Guinea-Bissau',
  GTM: 'Guatemala',
  HND: 'Honduras',
  HTI: 'Haiti',
  IDN: 'Indonesia',
  IND: 'India',
  IRN: 'Iran',
  IRQ: 'Iraq',
  ISR: 'Israel',
  KEN: 'Kenya',
  KGZ: 'Kyrgyzstan',
  LBN: 'Lebanon',
  LBY: 'Libya',
  MDG: 'Madagascar',
  MEX: 'Mexico',
  MLI: 'Mali',
  MMR: 'Myanmar',
  MOZ: 'Mozambique',
  NER: 'Niger',
  NGA: 'Nigeria',
  PAK: 'Pakistan',
  PHL: 'Philippines',
  PSE: 'Palestine',
  RUS: 'Russia',
  SAU: 'Saudi Arabia',
  SDN: 'Sudan',
  SEN: 'Senegal',
  SLE: 'Sierra Leone',
  SOM: 'Somalia',
  SSD: 'South Sudan',
  SYR: 'Syria',
  TCD: 'Chad',
  TGO: 'Togo',
  THA: 'Thailand',
  TJK: 'Tajikistan',
  TUN: 'Tunisia',
  TUR: 'Türkiye',
  UGA: 'Uganda',
  UKR: 'Ukraine',
  VEN: 'Venezuela',
  YEM: 'Yemen',
  ZWE: 'Zimbabwe',
};

export function getCountryName(iso3: string): string {
  return COUNTRY_NAMES[iso3] ?? iso3;
}
